language: python

python:
  - "2.7"

env:
 - VERSION="7.0" ODOO_REPO="odoo/odoo" EXCLUDE="invoice_validation_wkfl"
 - VERSION="7.0" ODOO_REPO="OCA/OCB" EXCLUDE="invoice_validation_wkfl"
 - VERSION="7.0" ODOO_REPO="odoo/odoo" INCLUDE="invoice_validation_wkfl"
 - VERSION="7.0" ODOO_REPO="OCA/OCB" INCLUDE="invoice_validation_wkfl"
 - VERSION="7.0" UNIT_TEST="1"

virtualenv:
  system_site_packages: true

before_install:
  - git clone https://github.com/akretion/stock-logistics-workflow.git $HOME/stock-logistics-workflow -b 7.0-picking-line-sale-link

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - git clone https://github.com/OCA/account-financial-tools.git -b ${VERSION} ${HOME}/account-financial-tools
  - git clone https://github.com/OCA/product-attribute.git -b ${VERSION} ${HOME}/product-attribute
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  coveralls
